import { BookAbbr } from "./types";

export const BOOK_TO_ABBR: Record<string, BookAbbr> = {
    "Gênesis": "gn",
    "gn": "gn",
    "Êxodo": "ex",
    "ex": "ex",
    "Levítico": "lv",
    "lv": "lv",
    "Números": "nm",
    "nm": "nm",
    "Deuteronômio": "dt",
    "dt": "dt",
    "Josué": "js",
    "js": "js",
    "Juízes": "jz",
    "jz": "jz",
    "Rute": "rt",
    "rt": "rt",
    "1 Samuel": "1sm",
    "1sm": "1sm",
    "2 Samuel": "2sm",
    "2sm": "2sm",
    "1 Reis": "1rs",
    "1rs": "1rs",
    "2 Reis": "2rs",
    "2rs": "2rs",
    "1 Crônicas": "1cr",
    "1cr": "1cr",
    "2 Crônicas": "2cr",
    "2cr": "2cr",
    "Esdras": "ed",
    "ed": "ed",
    "Neemias": "ne",
    "ne": "ne",
    "Ester": "et",
    "et": "et",
    "Jó": "jó",
    "jó": "jó",
    "Salmos": "sl",
    "sl": "sl",
    "Provérbios": "pv",
    "pv": "pv",
    "Eclesiastes": "ec",
    "ec": "ec",
    "Cantares": "ct",
    "ct": "ct",
    "Isaías": "is",
    "is": "is",
    "Jeremias": "jr",
    "jr": "jr",
    "Lamentações": "lm",
    "lm": "lm",
    "Ezequiel": "ez",
    "ez": "ez",
    "Daniel": "dn",
    "dn": "dn",
    "Oséias": "os",
    "os": "os",
    "Joel": "jl",
    "jl": "jl",
    "Amós": "am",
    "am": "am",
    "Obadias": "ob",
    "ob": "ob",
    "Jonas": "jn",
    "jn": "jn",
    "Miquéias": "mq",
    "mq": "mq",
    "Naum": "na",
    "na": "na",
    "Habacuque": "hc",
    "hc": "hc",
    "Sofonias": "sf",
    "sf": "sf",
    "Ageu": "ag",
    "ag": "ag",
    "Zacarias": "zc",
    "zc": "zc",
    "Malaquias": "ml",
    "ml": "ml",
    "Mateus": "mt",
    "mt": "mt",
    "Marcos": "mc",
    "mc": "mc",
    "Lucas": "lc",
    "lc": "lc",
    "João": "jo",
    "jo": "jo",
    "Atos": "at",
    "at": "at",
    "Romanos": "rm",
    "rm": "rm",
    "1 Coríntios": "1co",
    "1co": "1co",
    "2 Coríntios": "2co",
    "2co": "2co",
    "Gálatas": "gl",
    "gl": "gl",
    "Efésios": "ef",
    "ef": "ef",
    "Filipenses": "fp",
    "fp": "fp",
    "Colossenses": "cl",
    "cl": "cl",
    "1 Tessalonicenses": "1ts",
    "1ts": "1ts",
    "2 Tessalonicenses": "2ts",
    "2ts": "2ts",
    "1 Timóteo": "1tm",
    "1tm": "1tm",
    "2 Timóteo": "2tm",
    "2tm": "2tm",
    "Tito": "tt",
    "tt": "tt",
    "Filemom": "fm",
    "fm": "fm",
    "Hebreus": "hb",
    "hb": "hb",
    "Tiago": "tg",
    "tg": "tg",
    "1 Pedro": "1pe",
    "1pe": "1pe",
    "2 Pedro": "2pe",
    "2pe": "2pe",
    "1 João": "1jo",
    "1jo": "1jo",
    "2 João": "2jo",
    "2jo": "2jo",
    "3 João": "3jo",
    "3jo": "3jo",
    "Judas": "jd",
    "jd": "jd",
    "Apocalipse": "ap",
    "ap": "ap",
}

export const ABBR_TO_BOOK: Record<BookAbbr, string> = {
    "gn": "Gênesis",
    "ex": "Êxodo",
    "lv": "Levítico",
    "nm": "Números",
    "dt": "Deuteronômio",
    "js": "Josué",
    "jz": "Juízes",
    "rt": "Rute",
    "1sm": "1 Samuel",
    "2sm": "2 Samuel",
    "1rs": "1 Reis",
    "2rs": "2 Reis",
    "1cr": "1 Crônicas",
    "2cr": "2 Crônicas",
    "ed": "Esdras",
    "ne": "Neemias",
    "et": "Ester",
    "jó": "Jó",
    "sl": "Salmos",
    "pv": "Provérbios",
    "ec": "Eclesiastes",
    "ct": "Cantares",
    "is": "Isaías",
    "jr": "Jeremias",
    "lm": "Lamentações",
    "ez": "Ezequiel",
    "dn": "Daniel",
    "os": "Oséias",
    "jl": "Joel",
    "am": "Amós",
    "ob": "Obadias",
    "jn": "Jonas",
    "mq": "Miquéias",
    "na": "Naum",
    "hc": "Habacuque",
    "sf": "Sofonias",
    "ag": "Ageu",
    "zc": "Zacarias",
    "ml": "Malaquias",
    "mt": "Mateus",
    "mc": "Marcos",
    "lc": "Lucas",
    "jo": "João",
    "at": "Atos",
    "rm": "Romanos",
    "1co": "1 Coríntios",
    "2co": "2 Coríntios",
    "gl": "Gálatas",
    "ef": "Efésios",
    "fp": "Filipenses",
    "cl": "Colossenses",
    "1ts": "1 Tessalonicenses",
    "2ts": "2 Tessalonicenses",
    "1tm": "1 Timóteo",
    "2tm": "2 Timóteo",
    "tt": "Tito",
    "fm": "Filemom",
    "hb": "Hebreus",
    "tg": "Tiago",
    "1pe": "1 Pedro",
    "2pe": "2 Pedro",
    "1jo": "1 João",
    "2jo": "2 João",
    "3jo": "3 João",
    "jd": "Judas",
    "ap": "Apocalipse",
}

export const REFERENCE_EVENT = 'reference-event'